
package vista;

import java.awt.Dimension;
import javax.swing.JDesktopPane;

/**
 *
 * @author MATIAS
 */
public class FrmMenu extends javax.swing.JFrame {

  public static JDesktopPane jDesktopPane_menu;
    public FrmMenu() {
        initComponents();
        this.setSize(new Dimension(1200,700));
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("Sistema de Ventas");
        
        this.setLayout(null);
        jDesktopPane_menu =  new JDesktopPane();
        
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
        this.jDesktopPane_menu.setBounds(0,0,ancho, (alto-110));
        this.add(jDesktopPane_menu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1_nuevoMenu = new javax.swing.JMenuItem();
        jMenuItem2_gestionarUsuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4_nuevoProducto = new javax.swing.JMenuItem();
        jMenuItem5_gestionarProducto = new javax.swing.JMenuItem();
        jMenuItem18_actualizar_stock = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6_nuevo_cliente = new javax.swing.JMenuItem();
        jMenuItem7_gestionar_cliente = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem8_nueva_categoria = new javax.swing.JMenuItem();
        jMenuItem9_gestionar_categoria = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem10_nueva_Venta = new javax.swing.JMenuItem();
        jMenuItem11_gestionar_venta = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem12_repprte_cliente = new javax.swing.JMenuItem();
        jMenuItem13_reporte_categoria = new javax.swing.JMenuItem();
        jMenuItem14_reporte_Productos = new javax.swing.JMenuItem();
        jMenuItem15_reporte_ventas = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem16_histotial = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem17_cerrar_Sesion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        jMenu1.setText("Usuario");
        jMenu1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu1.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem1_nuevoMenu.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem1_nuevoMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-cliente.png"))); // NOI18N
        jMenuItem1_nuevoMenu.setText("Nuevo Usuario");
        jMenu1.add(jMenuItem1_nuevoMenu);

        jMenuItem2_gestionarUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem2_gestionarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuraciones.png"))); // NOI18N
        jMenuItem2_gestionarUsuario.setText("Gestionar Usuario");
        jMenu1.add(jMenuItem2_gestionarUsuario);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producto.png"))); // NOI18N
        jMenu2.setText("Producto");
        jMenu2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu2.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem4_nuevoProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem4_nuevoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-producto.png"))); // NOI18N
        jMenuItem4_nuevoProducto.setText("Nuevo Producto");
        jMenuItem4_nuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4_nuevoProductoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4_nuevoProducto);

        jMenuItem5_gestionarProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem5_gestionarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/producto.png"))); // NOI18N
        jMenuItem5_gestionarProducto.setText("Gestionar Producto");
        jMenuItem5_gestionarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5_gestionarProductoActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5_gestionarProducto);

        jMenuItem18_actualizar_stock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem18_actualizar_stock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        jMenuItem18_actualizar_stock.setText("Actualizar Stock");
        jMenu2.add(jMenuItem18_actualizar_stock);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cliente.png"))); // NOI18N
        jMenu3.setText("Cliente");
        jMenu3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu3.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem6_nuevo_cliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem6_nuevo_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo-cliente.png"))); // NOI18N
        jMenuItem6_nuevo_cliente.setText("Nuevo Cliente");
        jMenu3.add(jMenuItem6_nuevo_cliente);

        jMenuItem7_gestionar_cliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem7_gestionar_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clientes.png"))); // NOI18N
        jMenuItem7_gestionar_cliente.setText("Gestionar Cliente");
        jMenuItem7_gestionar_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7_gestionar_clienteActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7_gestionar_cliente);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorias.png"))); // NOI18N
        jMenu4.setText("Categoria");
        jMenu4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu4.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem8_nueva_categoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem8_nueva_categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        jMenuItem8_nueva_categoria.setText("Nueva Categoria");
        jMenuItem8_nueva_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8_nueva_categoriaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8_nueva_categoria);

        jMenuItem9_gestionar_categoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem9_gestionar_categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/categorias.png"))); // NOI18N
        jMenuItem9_gestionar_categoria.setText("Gestionar Categoria");
        jMenuItem9_gestionar_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9_gestionar_categoriaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9_gestionar_categoria);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/carrito.png"))); // NOI18N
        jMenu5.setText("Ventas");
        jMenu5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu5.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem10_nueva_Venta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem10_nueva_Venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/anadir.png"))); // NOI18N
        jMenuItem10_nueva_Venta.setText("Nueva Venta");
        jMenu5.add(jMenuItem10_nueva_Venta);

        jMenuItem11_gestionar_venta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem11_gestionar_venta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/configuraciones.png"))); // NOI18N
        jMenuItem11_gestionar_venta.setText("Gestionar Venta");
        jMenu5.add(jMenuItem11_gestionar_venta);

        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte1.png"))); // NOI18N
        jMenu6.setText("Reportes");
        jMenu6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu6.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem12_repprte_cliente.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem12_repprte_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte1.png"))); // NOI18N
        jMenuItem12_repprte_cliente.setText("Reporte Clientes");
        jMenu6.add(jMenuItem12_repprte_cliente);

        jMenuItem13_reporte_categoria.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem13_reporte_categoria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte1.png"))); // NOI18N
        jMenuItem13_reporte_categoria.setText("Reporte Categoria");
        jMenu6.add(jMenuItem13_reporte_categoria);

        jMenuItem14_reporte_Productos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem14_reporte_Productos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte1.png"))); // NOI18N
        jMenuItem14_reporte_Productos.setText("Reporte Productos");
        jMenu6.add(jMenuItem14_reporte_Productos);

        jMenuItem15_reporte_ventas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jMenuItem15_reporte_ventas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte1.png"))); // NOI18N
        jMenuItem15_reporte_ventas.setText("Reporte Ventas");
        jMenu6.add(jMenuItem15_reporte_ventas);

        jMenuBar1.add(jMenu6);

        jMenu7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/historial1.png"))); // NOI18N
        jMenu7.setText("Historial");
        jMenu7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu7.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem16_histotial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItem16_histotial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/historial1.png"))); // NOI18N
        jMenuItem16_histotial.setText("Ver Historial");
        jMenu7.add(jMenuItem16_histotial);

        jMenuBar1.add(jMenu7);

        jMenu8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        jMenu8.setText("Cerrar");
        jMenu8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMenu8.setMinimumSize(new java.awt.Dimension(180, 50));
        jMenu8.setPreferredSize(new java.awt.Dimension(150, 50));

        jMenuItem17_cerrar_Sesion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jMenuItem17_cerrar_Sesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar-sesion.png"))); // NOI18N
        jMenuItem17_cerrar_Sesion.setText("Cerar Sesion");
        jMenu8.add(jMenuItem17_cerrar_Sesion);

        jMenuBar1.add(jMenu8);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem9_gestionar_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9_gestionar_categoriaActionPerformed
        InterGestionarCategoria interGestionarCategoria = new InterGestionarCategoria();
        jDesktopPane_menu.add(interGestionarCategoria);
        interGestionarCategoria.setVisible(true);
    }//GEN-LAST:event_jMenuItem9_gestionar_categoriaActionPerformed

    private void jMenuItem7_gestionar_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7_gestionar_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7_gestionar_clienteActionPerformed

    private void jMenuItem8_nueva_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8_nueva_categoriaActionPerformed
        IntrCategoria intercategoria = new IntrCategoria();
        jDesktopPane_menu.add(intercategoria);
       intercategoria.setVisible(true);
    }//GEN-LAST:event_jMenuItem8_nueva_categoriaActionPerformed

    private void jMenuItem4_nuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4_nuevoProductoActionPerformed
        InterProducto interproducto = new InterProducto();
        jDesktopPane_menu.add(interproducto);
       interproducto.setVisible(true);
    }//GEN-LAST:event_jMenuItem4_nuevoProductoActionPerformed

    private void jMenuItem5_gestionarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5_gestionarProductoActionPerformed
        InterGestionarProducto interGestionarProducto = new InterGestionarProducto();
        jDesktopPane_menu.add(interGestionarProducto);
        interGestionarProducto.setVisible(true);
    }//GEN-LAST:event_jMenuItem5_gestionarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10_nueva_Venta;
    private javax.swing.JMenuItem jMenuItem11_gestionar_venta;
    private javax.swing.JMenuItem jMenuItem12_repprte_cliente;
    private javax.swing.JMenuItem jMenuItem13_reporte_categoria;
    private javax.swing.JMenuItem jMenuItem14_reporte_Productos;
    private javax.swing.JMenuItem jMenuItem15_reporte_ventas;
    private javax.swing.JMenuItem jMenuItem16_histotial;
    private javax.swing.JMenuItem jMenuItem17_cerrar_Sesion;
    private javax.swing.JMenuItem jMenuItem18_actualizar_stock;
    private javax.swing.JMenuItem jMenuItem1_nuevoMenu;
    private javax.swing.JMenuItem jMenuItem2_gestionarUsuario;
    private javax.swing.JMenuItem jMenuItem4_nuevoProducto;
    private javax.swing.JMenuItem jMenuItem5_gestionarProducto;
    private javax.swing.JMenuItem jMenuItem6_nuevo_cliente;
    private javax.swing.JMenuItem jMenuItem7_gestionar_cliente;
    private javax.swing.JMenuItem jMenuItem8_nueva_categoria;
    private javax.swing.JMenuItem jMenuItem9_gestionar_categoria;
    // End of variables declaration//GEN-END:variables
}
